"""Regenerate Fatima's scoring fixtures through the deterministic engine."""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator

from scoring.score_crops import score_crops
from scoring.validate_recommendations import validate_ranking_contract


ROOT = Path(__file__).resolve().parents[1]
HANDOFF = ROOT / "handoff" / "fatima_scoring_migrations"


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def save_json(path: Path, value: dict[str, Any]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, indent=2, ensure_ascii=False, allow_nan=False)
        handle.write("\n")


def invalid_numeric_count(value: Any) -> int:
    if isinstance(value, float):
        return 0 if math.isfinite(value) else 1
    if isinstance(value, dict):
        return sum(invalid_numeric_count(item) for item in value.values())
    if isinstance(value, list):
        return sum(invalid_numeric_count(item) for item in value)
    return 0


def main() -> None:
    profile = load_json(HANDOFF / "sample_engine_input.json")
    evidence = load_json(HANDOFF / "sample_evidence_bundle.json")
    config = load_json(HANDOFF / "sample_scoring_config.json")
    recommendation_schema = load_json(HANDOFF / "schemas" / "recommendation.schema.json")
    evidence_schema = load_json(HANDOFF / "schemas" / "evidence_bundle.schema.json")

    output = score_crops(evidence, profile, config)
    output_schema_errors = sorted(
        Draft202012Validator(recommendation_schema).iter_errors(output),
        key=lambda error: list(error.absolute_path),
    )
    evidence_schema_errors = sorted(
        Draft202012Validator(evidence_schema).iter_errors(evidence),
        key=lambda error: list(error.absolute_path),
    )
    ranking_validation = validate_ranking_contract(output)
    if output_schema_errors or evidence_schema_errors or not ranking_validation["eligibility_ranking_policy_passed"]:
        messages = [error.message for error in evidence_schema_errors + output_schema_errors]
        failed_checks = [
            name for name, passed in ranking_validation.items()
            if name.endswith("_valid") and passed is False
        ]
        raise ValueError(f"Handoff validation failed: schema={messages}; policy={failed_checks}")

    save_json(HANDOFF / "sample_22_crop_engine_output.json", output)
    report = {
        "report_version": "1.1.0",
        "sample": "plainview",
        "evidence_bundle_id": evidence["bundle_id"],
        "profile_id": profile["profile_id"],
        "scoring_version": config["scoring_version"],
        "status": "validated",
        "evidence_bundle_validation": {
            **evidence["validation"],
            "schema_error_count": len(evidence_schema_errors),
        },
        "engine_output_validation": {
            "schema": "schemas/recommendation.schema.json",
            "passed": not output_schema_errors and ranking_validation["eligibility_ranking_policy_passed"],
            **ranking_validation,
            "schema_error_count": len(output_schema_errors),
            "invalid_numeric_value_count": invalid_numeric_count(output),
        },
        "notes": [
            "Generated by scripts/regenerate_scoring_handoff.py through the deterministic scoring engine.",
            "All 22 crops are returned; regional eligibility controls ranking groups and eligible_rank.",
            "This report is a database handoff sample, not an agronomic approval.",
        ],
    }
    save_json(HANDOFF / "sample_validation_report.json", report)
    print(f"Generated scoring fixture for engine {config['scoring_version']}")
    print(f"Eligible crops: {ranking_validation['eligible_crop_count']}; ineligible crops: {ranking_validation['ineligible_crop_count']}")
    print(f"Saved: {HANDOFF / 'sample_22_crop_engine_output.json'}")
    print(f"Saved: {HANDOFF / 'sample_validation_report.json'}")


if __name__ == "__main__":
    main()
